INCLUDE "DEVICE.asm"

INCLUDE "DEFAULTS.asm"

MACRO BASE_NAME
    EQUS "Model B "
    SYSTEM_NAME
IF _DEVICE_="U2" OR _DEVICE_="T2"
    EQUS " (FE80)"
ENDIF
IF _DEVICE_="U3" OR _DEVICE_="T3"
    EQUS " (FEA0)"
ENDIF
ENDMACRO

INCLUDE "mmfs100.asm"
