INCLUDE "DEVICE.asm"

_SWRAM_=TRUE            ; Sideways RAM Version

IF _DEVICE_ = "1"
    _ROMS_=TRUE
ELSE
    _ROMS_=FALSE
ENDIF

INCLUDE "DEFAULTS.asm"

MACRO BASE_NAME
    EQUS "Model B "
    SYSTEM_NAME
    EQUS " SWRAM"
IF _DEVICE_="U2" OR _DEVICE_="T2"
    EQUS " (FE80)"
ENDIF
IF _DEVICE_="U3" OR _DEVICE_="T3"
    EQUS " (FEA0)"
ENDIF
ENDMACRO

INCLUDE "mmfs100.asm"
